apiVersion: v1
kind: Service
metadata: 
  name: frontend
  namespace: three-tier
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 3000
    protocol: TCP
  selector:
    role: frontend
